let btn_add = document.querySelector('#btn_add');
let input = document.querySelector('#sample1');
let productList = document.querySelector('#productList');
let btn_borrar = document.querySelector("#btn_borrar");
let cart = new Map();
let btnCargar = document.querySelector("#btnCargar");
let btnGuardar = document.querySelector("#btnGuardar");
let btnLimpiar = document.querySelector("#btnLimpiar");
let items = [];